config/routes.rb
Rails.application.routes.draw do
  resources :ruby_data
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ruby_datum.rb
class RubyDatum < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ruby_data_controller.rb
class RubyDataController < ApplicationController
  before_action :set_ruby_datum, only: %i[ show edit update destroy ]

  # GET /ruby_data or /ruby_data.json
  def index
    @ruby_data = RubyDatum.all
  end

  # GET /ruby_data/1 or /ruby_data/1.json
  def show
  end

  # GET /ruby_data/new
  def new
    @ruby_datum = RubyDatum.new
  end

  # GET /ruby_data/1/edit
  def edit
  end

  # POST /ruby_data or /ruby_data.json
  def create
    @ruby_datum = RubyDatum.new(ruby_datum_params)
    
    couldBeFloat = false
    couldBeInt = true

    if @ruby_datum.valInput.include? "."
      couldBeFloat = true
      couldBeInt = false
    end
    
    if couldBeInt
      @ruby_datum.rubyType = "Integer"
      !!Integer(@ruby_datum.valInput) rescue @ruby_datum.rubyType = "String"
    end

    if couldBeFloat
      @ruby_datum.rubyType = "Float"
      !!Float(@ruby_datum.valInput) rescue @ruby_datum.rubyType = "String"
    end

    respond_to do |format|
      if @ruby_datum.save
        format.html { redirect_to @ruby_datum, notice: "Ruby datum was successfully created." }
        format.json { render :show, status: :created, location: @ruby_datum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ruby_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ruby_data/1 or /ruby_data/1.json
  def update
    respond_to do |format|
      if @ruby_datum.update(ruby_datum_params)
        format.html { redirect_to @ruby_datum, notice: "Ruby datum was successfully updated." }
        format.json { render :show, status: :ok, location: @ruby_datum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ruby_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ruby_data/1 or /ruby_data/1.json
  def destroy
    @ruby_datum.destroy
    respond_to do |format|
      format.html { redirect_to ruby_data_url, notice: "Ruby datum was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ruby_datum
      @ruby_datum = RubyDatum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ruby_datum_params
      params.require(:ruby_datum).permit(:valInput,:rubyType)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ruby_data_helper.rb
module RubyDataHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LabBdRuby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ruby_data/_form.html.erb
<%= form_with(model: ruby_datum) do |form| %>
  <% if ruby_datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ruby_datum.errors.count, "error") %> prohibited this ruby_datum from being saved:</h2>

      <ul>
        <% ruby_datum.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :valInput %>
    <%= form.text_field :valInput %>
  </div>

  <div class="field">
    <%= form.label :rubyType %>
    <%= form.text_field :rubyType %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ruby_data/edit.html.erb
<h1>Editing Ruby Datum</h1>

<%= render 'form', ruby_datum: @ruby_datum %>

<%= link_to 'Show', @ruby_datum %> |
<%= link_to 'Back', ruby_data_path %>

app/views/ruby_data/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ruby Data</h1>

<table>
  <thead>
    <tr>
      <th>Valinput</th>
      <th>Rubytype</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ruby_data.each do |ruby_datum| %>
      <tr>
        <td><%= ruby_datum.valInput %></td>
        <td><%= ruby_datum.rubyType %></td>
        <td><%= link_to 'Show', ruby_datum %></td>
        <td><%= link_to 'Edit', edit_ruby_datum_path(ruby_datum) %></td>
        <td><%= link_to 'Destroy', ruby_datum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ruby Datum', new_ruby_datum_path %>

app/views/ruby_data/new.html.erb
<h1>New Ruby Datum</h1>

<%= form_with scope: :ruby_datum, local: true, url: ruby_data_path do |form| %>
    <%= form.label :valInput %> <%= form.text_field :valInput %>
    <%=form.submit("Criar") %> <%end%>

<%= link_to 'Back', ruby_data_path %>

app/views/ruby_data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Valinput:</strong>
  <%= @ruby_datum.valInput %>
</p>

<p>
  <strong>Rubytype:</strong>
  <%= @ruby_datum.rubyType %>
</p>

<%= link_to 'Edit', edit_ruby_datum_path(@ruby_datum) %> |
<%= link_to 'Back', ruby_data_path %>